inventories:
  example:
    title: "Example title"
    rows: 5
    items:
      gray_panel:
        material: "GRAY_STAINED_GLASS_PANE"
        slots: [ "0-26" ]
      red_panel:
        material: "RED_STAINED_GLASS_PANE"
        slots: [ "28-34" ]
      message:
        material: "PAPER"
        slot: 10
        leftClickActions:
          - "[message] &aMessage found"
      close:
        material: "PAPER"
        slot: 31
        displayName: "&4&lClose"
        leftClickActions:
          - "[sound] BLOCK_CHEST_CLOSE"


messages:
  onlyPlayers: "&cOnly players can be execute this command."
  emptyArgs: "&cThe sub command is empty."
  invalidArgs: "&cThe sub command is invalid."
  reloaded: "&aReloaded."
  emptyInventoryName: "&cThe inventory name is empty."
  invalidInventoryName: "&cThe inventory name is invalid or not exist."
  inventoryRegistered: "&aThe inventory has been registered."
  inventoryUnregistered: "&aThe inventory has been unregistered."
  inventoryOpened: "&aThe inventory has been opened."